services:
  cicd-service:
    image: docker.io/toxiccuss/cicd-service:0.0.2
    container_name: cicd-service
    restart: unless-stopped
    networks:
      proxy-network:
    mem_limit: 2g      # max. 512 MB RAM
    cpus: "4.00"
networks:
  proxy-network:
    external: true
